version: '3.8'

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: docker7904/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./static:/app/collected_static/
      - ./media:/app/media/

  frontend:
    image: docker7904/kittygram_frontend
    volumes:
      - ./frontend:/app/build/

  gateway:
    image: docker7904/kittygram_gateway
    ports:
      - "80:80"
    volumes:
      - ./static:/var/html/static/
      - ./media:/var/html/media/
      - ./frontend:/usr/share/nginx/html/
    depends_on:
      - backend
      - frontend

volumes:
  pg_data: