version: '3.8'

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: docker7904/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./static:/app/collected_static/
      - ./media:/app/media/

  frontend:
    image: docker7904/kittygram_frontend
    # Используем sh -c, чтобы выполнить копирование и оставить контейнер запущенным
    command: sh -c "cp -r /app/build/. /frontend_static/ && sleep infinity"
    volumes:
      - ./frontend:/frontend_static/

  gateway:
    image: docker7904/kittygram_gateway
    ports:
      - "80:80"
    volumes:
      # Прокидываем статику бэкенда туда, где её ждет Nginx
      - ./static:/var/html/static/
      # Прокидываем медиафайлы
      - ./media:/var/html/media/
      # Прокидываем фронтенд по стандартному пути Nginx
      - ./frontend:/usr/share/nginx/html/
    depends_on:
      - backend
      - frontend

volumes:
  pg_data: